services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=upload
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
      - "4983:4983"
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DATABASE_URL=postgresql://docker:docker@pg:5432/upload
      - CLOUDFLARE_ACCOUNT_ID=c9538547746e22576239d91cb6bce296
      - CLOUDFLARE_ACCESS_KEY_ID=9b66895037c8f183f86bf2a340f6ac3c
      - CLOUDFLARE_SECRET_ACCESS_KEY=fcdeab9a8e6009baa6af4443395ab7b1a0e5dff3947d2580a19394a69e038072
      - CLOUDFLARE_BUCKET=upload-serv
      - CLOUDFLARE_PUBLIC_URL=https://pub-81f0c40746404e118ea21c560e0f29ff.r2.dev/
    depends_on:
      pg:
        condition: service_healthy
    restart: unless-stopped
